In [0]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
!free -g

              total        used        free      shared  buff/cache   available
Mem:             12           0          10           0           1          12
Swap:             0           0           0


In [0]:
import pandas as pd

#destinations = pd.read_csv("/content/drive/My Drive/Colab Notebooks/dataset/destinations.csv")
#test = pd.read_csv("/content/drive/My Drive/Colab Notebooks/dataset/test.csv")
#train = pd.read_csv("/content/drive/My Drive/Colab Notebooks/dataset/ds_train.csv")

print(train.shape)
display(train.head(5))
print(test.shape)
display(test.head(5))

(319954, 27)


Unnamed: 0            date_time  site_name  posa_continent  \
0        4828  2014-02-25 11:04:58          2               3   
1        4829  2014-02-25 11:21:28          2               3   
2        4830  2014-02-25 11:23:23          2               3   
3        4831  2014-02-25 11:25:51          2               3   
4        4832  2014-02-25 12:03:18          2               3   

   user_location_country  user_location_region  user_location_city  \
0                     66                   348               24562   
1                     66                   348               24562   
2                     66                   348               24562   
3                     66                   348               24562   
4                     66                   348               24562   

   orig_destination_distance  user_id  is_mobile  ...    srch_destination_id  \
0                   520.6930    30659          0  ...                   8229   
1                   513.1433    30659          0  ...                  26366   
2                   512.9470    30659          0  ...                  26366   
3                   512.9470    30659          0  ...                  26366   
4                   512.6471    30659          0  ...                  26366   

   srch_destination_type_id is_booking cnt  hotel_continent  hotel_country  \
0                         1          0   1                2             50   
1                         6          0   1                2             50   
2                         6          0   2                2             50   
3                         6          0   1                2             50   
4                         6          0   1                2             50   

   hotel_market  hotel_cluster  year  month  
0           678             25  2014      2  
1           678             76  2014      2  
2           678             33  2014      2  
3           678             33  2014      2  
4           678             59  2014      2  

[5 rows x 27 columns]

(2528243, 22)


id            date_time  site_name  posa_continent  user_location_country  \
0   0  2015-09-03 17:09:54          2               3                     66   
1   1  2015-09-24 17:38:35          2               3                     66   
2   2  2015-06-07 15:53:02          2               3                     66   
3   3  2015-09-14 14:49:10          2               3                     66   
4   4  2015-07-17 09:32:04          2               3                     66   

   user_location_region  user_location_city  orig_destination_distance  \
0                   174               37449                  5539.0567   
1                   174               37449                  5873.2923   
2                   142               17440                  3975.9776   
3                   258               34156                  1508.5975   
4                   467               36345                    66.7913   

   user_id  is_mobile      ...          srch_ci     srch_co srch_adults_cnt  \
0        1          1      ...       2016-05-19  2016-05-23               2   
1        1          1      ...       2016-05-12  2016-05-15               2   
2       20          0      ...       2015-07-26  2015-07-27               4   
3       28          0      ...       2015-09-14  2015-09-16               2   
4       50          0      ...       2015-07-22  2015-07-23               2   

  srch_children_cnt  srch_rm_cnt  srch_destination_id  \
0                 0            1                12243   
1                 0            1                14474   
2                 0            1                11353   
3                 0            1                 8250   
4                 0            1                11812   

   srch_destination_type_id  hotel_continent  hotel_country  hotel_market  
0                         6                6            204            27  
1                         7                6            204          1540  
2                         1                2             50           699  
3                         1                2             50           628  
4                         1                2             50           538  

[5 rows x 22 columns]

In [0]:
train = train[train.columns[:-2]]
train = train[train.columns[1:]]
train = train[train['is_booking']==True]

X_train = train[train.columns[:-1]]
y_train = train[train.columns[23:]]

#test = test[test.columns[:-2]]
#test = test[test.columns[1:]]
#test = test[test['is_booking']==True]

#X_test = test[test.columns[:-1]]
#y_test = test[test.columns[23:]]

(25150, 23)
(25150, 1)


date_time  site_name  posa_continent  user_location_country  \
11  2014-08-06 11:24:58          2               3                     66   
38  2013-02-17 20:18:18         37               1                     69   
45  2013-04-22 22:51:21         37               1                     69   
53  2014-01-02 20:52:26         37               1                     69   
71  2013-08-08 10:49:09          2               3                     66   

    user_location_region  user_location_city  orig_destination_distance  \
11                   348               24562                   520.3052   
38                   727               29821                        NaN   
45                  1003               54751                        NaN   
53                   581               23104                        NaN   
71                   220               13407                        NaN   

    user_id  is_mobile  is_package      ...       srch_adults_cnt  \
11    30659          0           0      ...                     2   
38    43845          0           1      ...                     2   
45    43845          0           0      ...                     2   
53    43845          0           0      ...                     2   
71    44526          0           0      ...                     1   

   srch_children_cnt srch_rm_cnt  srch_destination_id  \
11                 0           1                 8229   
38                 0           1                 8252   
45                 1           1                 8803   
53                 0           1                 8789   
71                 1           1                 8788   

    srch_destination_type_id  is_booking  cnt  hotel_continent  hotel_country  \
11                         1           1    1                2             50   
38                         1           1    1                6            170   
45                         1           1    1                3            151   
53                         1           1    1                0             63   
71                         1           1    1                6             77   

    hotel_market  
11           678  
38           313  
45            69  
53           962  
71             2  

[5 rows x 23 columns]

In [0]:
print(train.shape)
print(train.columns.values)
print(test.shape)
print(test.columns.values)

(25150, 24)
['date_time' 'site_name' 'posa_continent' 'user_location_country'
 'user_location_region' 'user_location_city' 'orig_destination_distance'
 'user_id' 'is_mobile' 'is_package' 'channel' 'srch_ci' 'srch_co'
 'srch_adults_cnt' 'srch_children_cnt' 'srch_rm_cnt' 'srch_destination_id'
 'srch_destination_type_id' 'is_booking' 'cnt' 'hotel_continent'
 'hotel_country' 'hotel_market' 'hotel_cluster']
(2528243, 22)
['id' 'date_time' 'site_name' 'posa_continent' 'user_location_country'
 'user_location_region' 'user_location_city' 'orig_destination_distance'
 'user_id' 'is_mobile' 'is_package' 'channel' 'srch_ci' 'srch_co'
 'srch_adults_cnt' 'srch_children_cnt' 'srch_rm_cnt' 'srch_destination_id'
 'srch_destination_type_id' 'hotel_continent' 'hotel_country'
 'hotel_market']


In [0]:
# Function to convert date object into relevant attributes
def convert_date_into_days(df):
    df['srch_ci'] = pd.to_datetime(df['srch_ci'], errors = 'coerce')
    df['srch_co'] = pd.to_datetime(df['srch_co'])
    df['date_time'] = pd.to_datetime(df['date_time'])
    
    df['stay_dur'] = (df['srch_co'] - df['srch_ci']).astype('timedelta64[D]')
    df['no_of_days_bet_booking'] = (df['srch_ci'] - df['date_time']).astype('timedelta64[D]')
    
    # For hotel check-in
    # Month, Year, Day
    df['Cin_day'] = df["srch_ci"].apply(lambda x: x.day)
    df['Cin_month'] = df["srch_ci"].apply(lambda x: x.month)
    df['Cin_year'] = df["srch_ci"].apply(lambda x: x.year)

In [0]:
convert_date_into_days(X_train)
display(X_train.head(5))

convert_date_into_days(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documenta

date_time  site_name  posa_continent  user_location_country  \
11 2014-08-06 11:24:58          2               3                     66   
38 2013-02-17 20:18:18         37               1                     69   
45 2013-04-22 22:51:21         37               1                     69   
53 2014-01-02 20:52:26         37               1                     69   
71 2013-08-08 10:49:09          2               3                     66   

    user_location_region  user_location_city  orig_destination_distance  \
11                   348               24562                   520.3052   
38                   727               29821                        NaN   
45                  1003               54751                        NaN   
53                   581               23104                        NaN   
71                   220               13407                        NaN   

    user_id  is_mobile  is_package    ...     is_booking cnt hotel_continent  \
11    30659          0           0    ...              1   1               2   
38    43845          0           1    ...              1   1               6   
45    43845          0           0    ...              1   1               3   
53    43845          0           0    ...              1   1               0   
71    44526          0           0    ...              1   1               6   

    hotel_country  hotel_market  stay_dur  no_of_days_bet_booking  Cin_day  \
11             50           678       3.0                     8.0       15   
38            170           313       4.0                    13.0        3   
45            151            69       2.0                   271.0       19   
53             63           962       1.0                    35.0        7   
71             77             2      14.0                     7.0       16   

    Cin_month  Cin_year  
11          8      2014  
38          3      2013  
45          1      2014  
53          2      2014  
71          8      2013  

[5 rows x 28 columns]

In [0]:
display(X_train.columns)
X_train.drop(columns=['date_time','srch_ci','srch_co'],inplace=True)
display(X_train.head(5))

#X_test.drop(columns=['date_time','srch_ci','srch_co'],inplace=True)

Index(['date_time', 'site_name', 'posa_continent', 'user_location_country',
       'user_location_region', 'user_location_city',
       'orig_destination_distance', 'user_id', 'is_mobile', 'is_package',
       'channel', 'srch_ci', 'srch_co', 'srch_adults_cnt', 'srch_children_cnt',
       'srch_rm_cnt', 'srch_destination_id', 'srch_destination_type_id',
       'is_booking', 'cnt', 'hotel_continent', 'hotel_country', 'hotel_market',
       'stay_dur', 'no_of_days_bet_booking', 'Cin_day', 'Cin_month',
       'Cin_year'],
      dtype='object')

site_name  posa_continent  user_location_country  user_location_region  \
11          2               3                     66                   348   
38         37               1                     69                   727   
45         37               1                     69                  1003   
53         37               1                     69                   581   
71          2               3                     66                   220   

    user_location_city  orig_destination_distance  user_id  is_mobile  \
11               24562                   520.3052    30659          0   
38               29821                        NaN    43845          0   
45               54751                        NaN    43845          0   
53               23104                        NaN    43845          0   
71               13407                        NaN    44526          0   

    is_package  channel    ...     is_booking  cnt  hotel_continent  \
11           0        9    ...              1    1                2   
38           1        1    ...              1    1                6   
45           0        1    ...              1    1                3   
53           0        0    ...              1    1                0   
71           0        9    ...              1    1                6   

    hotel_country  hotel_market  stay_dur  no_of_days_bet_booking  Cin_day  \
11             50           678       3.0                     8.0       15   
38            170           313       4.0                    13.0        3   
45            151            69       2.0                   271.0       19   
53             63           962       1.0                    35.0        7   
71             77             2      14.0                     7.0       16   

    Cin_month  Cin_year  
11          8      2014  
38          3      2013  
45          1      2014  
53          2      2014  
71          8      2013  

[5 rows x 25 columns]

In [0]:
X_train['Cin_day'] = X_train['Cin_day'].fillna(26.0)
X_train['Cin_month'] = X_train['Cin_month'].fillna(8.0)
X_train['Cin_year'] = X_train['Cin_year'].fillna(2014.0)
X_train['stay_dur'] = X_train['stay_dur'].fillna(1.0)
X_train['no_of_days_bet_booking'] = X_train['no_of_days_bet_booking'].fillna(0.0)
X_train['orig_destination_distance'].fillna(X_train['orig_destination_distance'].mean(), inplace=True)

display(X_train.head(5))
display(y_train.head(5))

#display(X_train.shape)
#display(y_train.shape)
#X_train = X_train[X_train['is_booking']==True]
#y_train = y_train[X_train['is_booking']==True]
#display(X_train.shape)
#display(y_train.shape)

site_name  posa_continent  user_location_country  user_location_region  \
11          2               3                     66                   348   
38         37               1                     69                   727   
45         37               1                     69                  1003   
53         37               1                     69                   581   
71          2               3                     66                   220   

    user_location_city  orig_destination_distance  user_id  is_mobile  \
11               24562                 520.305200    30659          0   
38               29821                1761.176739    43845          0   
45               54751                1761.176739    43845          0   
53               23104                1761.176739    43845          0   
71               13407                1761.176739    44526          0   

    is_package  channel    ...     is_booking  cnt  hotel_continent  \
11           0        9    ...              1    1                2   
38           1        1    ...              1    1                6   
45           0        1    ...              1    1                3   
53           0        0    ...              1    1                0   
71           0        9    ...              1    1                6   

    hotel_country  hotel_market  stay_dur  no_of_days_bet_booking  Cin_day  \
11             50           678       3.0                     8.0       15   
38            170           313       4.0                    13.0        3   
45            151            69       2.0                   271.0       19   
53             63           962       1.0                    35.0        7   
71             77             2      14.0                     7.0       16   

    Cin_month  Cin_year  
11          8      2014  
38          3      2013  
45          1      2014  
53          2      2014  
71          8      2013  

[5 rows x 25 columns]

hotel_cluster
11             28
38             12
45             29
53             25
71              2

### SVMs

In [0]:
from sklearn.svm import SVC
from sklearn import metrics

svcl = SVC(kernel='linear')
svcl.fit(X_train,y_train)



/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Factorization Machine

In [0]:
! pip install fastFM

    100% |████████████████████████████████| 491kB 18.6MB/s 
    100% |████████████████████████████████| 2.1MB 12.8MB/s 


In [0]:
display(X_train.columns.duplicated())
display(y_train.columns.duplicated())

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

array([False])

In [0]:
import scipy
from fastFM import als
fm = als.FMRegression(n_iter=1000, init_stdev=0.1, rank=2, l2_reg_w=0.1, l2_reg_V=0.5)

display(X_train.values)
X_t = scipy.sparse.csr_matrix(X_train.values)
display(X_t)
display(X_t.shape)
y_t = y_train.values
y_t = y_t.flatten()
display(y_t.shape)

fm.fit(X_t, y_t)
#y_pred = fm.predict(X_test)

array([[2.000e+00, 3.000e+00, 6.600e+01, ..., 1.700e+01, 4.000e+00,
        2.014e+03],
       [2.000e+00, 3.000e+00, 6.600e+01, ..., 1.800e+01, 4.000e+00,
        2.014e+03],
       [2.000e+00, 3.000e+00, 6.600e+01, ..., 1.800e+01, 4.000e+00,
        2.014e+03],
       ...,
       [2.000e+00, 3.000e+00, 6.600e+01, ..., 5.000e+00, 7.000e+00,
        2.014e+03],
       [2.000e+00, 3.000e+00, 6.600e+01, ..., 5.000e+00, 7.000e+00,
        2.014e+03],
       [2.000e+00, 3.000e+00, 6.600e+01, ..., 5.000e+00, 7.000e+00,
        2.014e+03]])

<319954x25 sparse matrix of type '<class 'numpy.float64'>'
	with 6861801 stored elements in Compressed Sparse Row format>

(319954, 25)

(319954,)

NameError: ignored

In [0]:
#X_te = scipy.sparse.csr_matrix(X_test.values)
y_pred = fm.predict(X_t)

In [0]:
display(X_train.head(5))
display(y_train.head(5))

from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X_train, y_train, test_size=0.33, random_state=42)

site_name  posa_continent  user_location_country  user_location_region  \
11          2               3                     66                   348   
38         37               1                     69                   727   
45         37               1                     69                  1003   
53         37               1                     69                   581   
71          2               3                     66                   220   

    user_location_city  orig_destination_distance  user_id  is_mobile  \
11               24562                 520.305200    30659          0   
38               29821                1761.176739    43845          0   
45               54751                1761.176739    43845          0   
53               23104                1761.176739    43845          0   
71               13407                1761.176739    44526          0   

    is_package  channel    ...     is_booking  cnt  hotel_continent  \
11           0        9    ...              1    1                2   
38           1        1    ...              1    1                6   
45           0        1    ...              1    1                3   
53           0        0    ...              1    1                0   
71           0        9    ...              1    1                6   

    hotel_country  hotel_market  stay_dur  no_of_days_bet_booking  Cin_day  \
11             50           678       3.0                     8.0       15   
38            170           313       4.0                    13.0        3   
45            151            69       2.0                   271.0       19   
53             63           962       1.0                    35.0        7   
71             77             2      14.0                     7.0       16   

    Cin_month  Cin_year  
11          8      2014  
38          3      2013  
45          1      2014  
53          2      2014  
71          8      2013  

[5 rows x 25 columns]

hotel_cluster
11             28
38             12
45             29
53             25
71              2

In [0]:
!pip uninstall xgboost
!pip3 install xgboost

Uninstalling xgboost-0.7.post4:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/xgboost-0.7.post4-py3.6.egg-info
    /usr/local/lib/python3.6/dist-packages/xgboost/*
Proceed (y/n)? y
  Successfully uninstalled xgboost-0.7.post4
    100% |████████████████████████████████| 16.6MB 1.9MB/s 


In [0]:
! pip install ml_metrics

  Running setup.py bdist_wheel for ml-metrics ... - \ | / done
  Stored in directory: /root/.cache/pip/wheels/b3/61/2d/776be7b8a4f14c5db48c8e5451451cabc58dc6aa7ee3801163
Successfully built ml-metrics


In [0]:
import ml_metrics as metrics

def map5eval(target,predictions):
  pred = predictions.argsort(axis=1)[:,-np.arange(1,6)]
  return metrics.mapk(target,pred,k=5)
  

### XGBoost

In [ ]:
##GridSearchCV Tuning
from xgboost import XGBClassifier
from sklearn.grid_search import GridSearchCV
from sklearn.cross_validation import StratifiedKFold

xgb_model = XGBClassifier()


parameters = {'tree_method': ["gpu_hist"], 
              'feval': ['map5eval']
              'objective':['multi:softmax'],
              'num_class': [100],
              'learning_rate': [0.03, 0.05, 0.08, 0.1, 0.12], 
              'max_depth': [4, 6, 8, 10],
              'min_child_weight': [7, 9, 11],
              'silent': [1],
              'subsample': [0.6, 0.8, 1.0],
              'colsample_bytree': [0.6, 0.7, 0.8, 1.0],
              'n_estimators': [10],
              'gamma': [0, 0.5, 1, 1.5, 2],
              'seed': [42]
               }

clf = GridSearchCV(xgb_model, parameters, n_jobs=5, 
                   cv=StratifiedKFold(ytrain.values.ravel(), n_folds=5, shuffle=True), 
                   verbose=2, refit=True)

#Use X_train, X_train_pca, X_train_trans(feature selection), X_train_combo(feature selection+pca)
clf.fit(Xtrain, ytrain)

#Selecting best parameters and showing CV score
best_params, score, _ = max(clf.grid_scores_, key=lambda x: x[1])
print('XGB Map5 Score:', score)
for param_name in sorted(best_params.keys()):
    print("%s: %r" % (param_name, best_params[param_name]))

In [7]:
##GridSearchCV Tuning
from xgboost import XGBClassifier
from sklearn.grid_search import GridSearchCV
from sklearn.cross_validation import StratifiedKFold

xgb_model = XGBClassifier()


parameters = {'tree_method': ["gpu_hist"], 
              'feval': ['map5eval'],
              'objective':['multi:softmax'],
              'num_class': [100],
              'learning_rate': [0.08], 
              'max_depth': [8],
              'min_child_weight': [9],
              'silent': [1],
              'subsample': [0.8],
              'colsample_bytree': [0.7],
              'n_estimators': [10],
              'seed': [42]
               }

clf = GridSearchCV(xgb_model, parameters, n_jobs=5, 
                   cv=StratifiedKFold(ytrain.values.ravel(), n_folds=5, shuffle=True), 
                   verbose=2, refit=True)

#Use X_train, X_train_pca, X_train_trans(feature selection), X_train_combo(feature selection+pca)
clf.fit(Xtrain, ytrain)

#Selecting best parameters and showing CV score
best_params, score, _ = max(clf.grid_scores_, key=lambda x: x[1])
print('XGB Map5 Score:', score)
for param_name in sorted(best_params.keys()):
    print("%s: %r" % (param_name, best_params[param_name]))

C:\Users\dar\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\dar\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


NameError: name 'ytrain' is not defined

In [0]:
import xgboost as xgb

xgb_params = {'tree_method': 'gpu_hist', 
              'objective':'multi:softmax',
              'num_class': 100,
              'learning_rate': 0.08,
              'max_depth': 8,
              'min_child_weight': 9,
              'silent': 1,
              'subsample': 0.8,
              'colsample_bytree': 0.7,
              'n_estimators': 600,
              'seed': 42
}

xgb_model = xgb.XGBClassifier(**xgb_params)
xgb_model.fit(Xtrain,ytrain)


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, eta=0.3, feval='map5eval', gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
       nthread=None, num_class=100, objective='multi:softprob',
       random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
       seed=None, silent=True, subsample=1)

In [0]:
ypred = xgb_model.predict_proba(Xtest)

In [0]:
print(map5eval(ytest.values,ypred))

0.25289156626506026


In [0]:
id = test['id']
print(id.shape)

print(test.shape)
tests = test[test.columns[1:]]
print(tests.shape)
display(tests.head(5))

tests['is_booking'] = 1
tests['cnt'] = 1
tests = tests[X_train.columns]

print(tests.columns)
print(X_train.columns)

ysub = xgb_model.predict_proba(tests)

(2528243,)
(2528243, 24)
(2528243, 23)


site_name  posa_continent  user_location_country  user_location_region  \
0          2               3                     66                   174   
1          2               3                     66                   174   
2          2               3                     66                   142   
3          2               3                     66                   258   
4          2               3                     66                   467   

   user_location_city  orig_destination_distance  user_id  is_mobile  \
0               37449                  5539.0567        1          1   
1               37449                  5873.2923        1          1   
2               17440                  3975.9776       20          0   
3               34156                  1508.5975       28          0   
4               36345                    66.7913       50          0   

   is_package  channel    ...     srch_destination_id  \
0           0        3    ...                   12243   
1           0       10    ...                   14474   
2           0        1    ...                   11353   
3           1       10    ...                    8250   
4           0        0    ...                   11812   

   srch_destination_type_id  hotel_continent  hotel_country  hotel_market  \
0                         6                6            204            27   
1                         7                6            204          1540   
2                         1                2             50           699   
3                         1                2             50           628   
4                         1                2             50           538   

   stay_dur  no_of_days_bet_booking  Cin_day  Cin_month  Cin_year  
0       4.0                   258.0     19.0        5.0    2016.0  
1       3.0                   230.0     12.0        5.0    2016.0  
2       1.0                    48.0     26.0        7.0    2015.0  
3       2.0                    -1.0     14.0        9.0    2015.0  
4       1.0                     4.0     22.0        7.0    2015.0  

[5 rows x 23 columns]

Index(['site_name', 'posa_continent', 'user_location_country',
       'user_location_region', 'user_location_city',
       'orig_destination_distance', 'user_id', 'is_mobile', 'is_package',
       'channel', 'srch_adults_cnt', 'srch_children_cnt', 'srch_rm_cnt',
       'srch_destination_id', 'srch_destination_type_id', 'is_booking', 'cnt',
       'hotel_continent', 'hotel_country', 'hotel_market', 'stay_dur',
       'no_of_days_bet_booking', 'Cin_day', 'Cin_month', 'Cin_year'],
      dtype='object')
Index(['site_name', 'posa_continent', 'user_location_country',
       'user_location_region', 'user_location_city',
       'orig_destination_distance', 'user_id', 'is_mobile', 'is_package',
       'channel', 'srch_adults_cnt', 'srch_children_cnt', 'srch_rm_cnt',
       'srch_destination_id', 'srch_destination_type_id', 'is_booking', 'cnt',
       'hotel_continent', 'hotel_country', 'hotel_market', 'stay_dur',
       'no_of_days_bet_booking', 'Cin_day', 'Cin_month', 'Cin_year'],
      dtype=

In [0]:
print(id.shape)
print(ysub.shape)
ysubf = ysub.argsort(axis=1)[:,-np.arange(1,6)]
print(ysub.shape)
print(ysub)

(2528243,)
(2528243, 100)
(2528243, 100)
[[0.00569278 0.00569087 0.01228159 ... 0.0260842  0.0095312  0.0322927 ]
 [0.00621456 0.00768141 0.01611426 ... 0.00747202 0.00680406 0.02301748]
 [0.02217671 0.00632947 0.01091622 ... 0.00843661 0.01064993 0.00692928]
 ...
 [0.00589883 0.09770291 0.00582261 ... 0.00586658 0.00743283 0.00522107]
 [0.00723386 0.00585698 0.00731054 ... 0.00676915 0.00902689 0.00640272]
 [0.00535928 0.00535897 0.00653513 ... 0.00760532 0.00703455 0.01017759]]


In [0]:
print(ysubf.shape)
print(ysubf)

(2528243, 5)
[[ 5 99 25 97 11]
 [11 45 62 99 25]
 [ 0 37 50 91 16]
 ...
 [45  1 79 24 17]
 [91 43 17 48 47]
 [85 36 62 61 82]]


In [0]:
write_p = [" ".join([str(l) for l in p]) for p in ysubf]
write_frame = ["{0},{1}".format(test["id"][i], write_p[i]) for i in range(len(ysubf))]
write_frame = ["id,hotel_cluster"] + write_frame
with open("/content/drive/My Drive/Colab Notebooks/predictions2.csv", "w+") as f:
    f.write("\n".join(write_frame))

In [0]:
#Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb_model = MultinomialNB(alpha=1)

nb_model.fit(abs(Xtrain),ytrain)

In [0]:
nb_pred = nb_model.predict_proba(Xtest)
print(map5eval(ytest.values,nb_pred))

0.02695381526104418
